export enum ResponseCode {
  USER_DOESNT_EXIST = "USER_DOESNT_EXIST",
  UNAUTHORIZED = "UNAUTHORIZED",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
